### PR TITLE
Remove errant about.md

### PR DESCRIPTION
**Pull request by maxjacobson**
- remove about.md, which creates an `/about` page that we don't really
  want
- Stop tracking Gemfile.lock

I don't believe that GitHub Pages cares what version of gems we actually
use, this is just for our local development. And locally we want to say
"just give me whatever GitHub pages uses" so that we can get a local
preview of how it'll look in production.

### CODE REVIEW

**Comment by javierjulio** [comment]
Looks good, thanks Max! Are you sure about the `Gemfile.lock` change? Despite what GitHub Pages might do, I don't think it affects deployments from my experience, it would help to make sure we all run the same versions, etc. for our sanity.

**Comment by maxjacobson** [comment]
I think so. I made this PR because I noticed the `about.md` that slipped through and wanted to remove it. When bundling, the `Gemfile.lock` changed, as github must have released some new version of the gem. To keep noise out of our PRs I think it makes sense to exclude this file.

From [this help page](https://help.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll#updating-the-github-pages-gem):

> Jekyll is an active open source project that is updated frequently. If the github-pages gem on your computer is out of date with the github-pages gem on the GitHub Pages server, your site may look different when built locally than when published on GitHub. To avoid this, regularly update the github-pages gem on your computer.

By keeping a `Gemfile.lock`, we can make sure that the version of jekyll we're using on our laptops is all consistent, but that won't make it consistent with what GitHub pages does.

**Comment by rachelober** [comment]
I agree with @javierjulio in that I am not sure that we'd want to exclude the Gemfile.lock but I would need to research it more before having a stronger opinion.

**Comment by javierjulio** [comment]
Thanks for sharing that! Makes sense. I'd prefer to automate where possible to help us especially with cases like that, rather than remove the lock file. We can enable Dependabot here which works great so we get a PR for when github-pages gem has a new release, we would just test/merge and deploys automatically. Then we'd all be in sync. 👍🏻 I find automating things like that cut down a lot of barriers and helps speed things up.

**Comment by maxjacobson** [comment]
Cool that sounds fine to me. How to set that up?

**Comment by javierjulio** [comment]
@maxjacobson I set it up now just for this repo only. We have our first update in #19 which is a security fix.

**Comment by maxjacobson** [comment]
Sick. I'll remove the gemfile parts form this repo

**Comment by maxjacobson** [comment]
From this PR * 😂

**Comment by maxjacobson** [comment]
No worries - thanks for merging.

**Pull request merged**
